apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stack-observability-devops-stack
resources:
- namespace.yaml
- configmap.yaml
- secret.yaml
- postgres.yaml
- clickhouse.yaml
- prometheus.yaml
- grafana.yaml
