apiVersion: v1
kind: Secret
metadata:
  name: fintech-backend-queue-secret
  namespace: stack-fintech-backend-queue
type: Opaque
stringData:
  POSTGRES_PASSWORD: postgres_secure_pass
  MINIO_ROOT_PASSWORD: password123
  RABBITMQ_DEFAULT_PASS: guest
