apiVersion: v1
kind: Secret
metadata:
  name: fintech-backend-queue-secret
  namespace: stack-fintech-backend-queue
type: Opaque
stringData:
  DEFAULT_USER: admin
  DEFAULT_PASSWORD: admin123
  POSTGRES_PASSWORD: admin123
  MINIO_ROOT_PASSWORD: admin123
  RABBITMQ_DEFAULT_PASS: admin123
