apiVersion: apps/v1
kind: Deployment
metadata:
  name: openmetadata
  namespace: stack-telemetry-governance-stack
  labels:
    app: openmetadata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openmetadata
  template:
    metadata:
      labels:
        app: openmetadata
    spec:
      containers:
      - name: openmetadata
        image: docker.getcollate.io/openmetadata/server:1.4.2
        ports:
        - containerPort: 8585
          name: http
        env:
        - name: DB_HOST
          value: "postgres"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "postgres"
        - name: DB_USER_PASSWORD
          value: "postgres"
---
apiVersion: v1
kind: Service
metadata:
  name: openmetadata
  namespace: stack-telemetry-governance-stack
  labels:
    app: openmetadata
spec:
  type: ClusterIP
  ports:
  - port: 8585
    targetPort: 8585
    name: http
  selector:
    app: openmetadata
