apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: stack-telemetry-governance-stack
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:v2.53.0
        ports:
        - containerPort: 9090
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: stack-telemetry-governance-stack
  labels:
    app: prometheus
spec:
  type: ClusterIP
  ports:
  - port: 9090
    targetPort: 9090
    name: http
  selector:
    app: prometheus
