apiVersion: v1
kind: Secret
metadata:
  name: telemetry-governance-stack-secret
  namespace: stack-telemetry-governance-stack
type: Opaque
stringData:
  DEFAULT_USER: lead_admin
  DEFAULT_PASSWORD: governanceKey888
  POSTGRES_PASSWORD: governanceKey888
  MINIO_ROOT_PASSWORD: governanceKey888
  RABBITMQ_DEFAULT_PASS: governanceKey888
