apiVersion: v1
kind: Secret
metadata:
  name: velocelog-lakehouse-secret
  namespace: stack-velocelog-lakehouse
type: Opaque
stringData:
  POSTGRES_PASSWORD: postgres_secure_pass
  MINIO_ROOT_PASSWORD: password123
  RABBITMQ_DEFAULT_PASS: guest
