apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
  namespace: stack-velocelog-lakehouse
  labels:
    app: spark-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-master
  template:
    metadata:
      labels:
        app: spark-master
    spec:
      containers:
      - name: spark-master
        image: apache/spark:3.5.1-python3
        command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master"]
        ports:
        - containerPort: 7077
          name: spark-rpc
        - containerPort: 8080
          name: master-ui
        env:
        - name: SPARK_NO_DAEMONIZE
          value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: spark-master
  namespace: stack-velocelog-lakehouse
  labels:
    app: spark-master
spec:
  type: ClusterIP
  ports:
  - port: 7077
    targetPort: 7077
    name: spark-rpc
  - port: 8080
    targetPort: 8080
    name: master-ui
  selector:
    app: spark-master
