name: velocelog
services:
  vscode:
    image: codercom/code-server:latest
    container_name: velocelog-vscode
    entrypoint:
    - /bin/sh
    - /home/coder/project/vscode/entrypoint.sh
    environment:
      AUTO_INSTALL_EXTENSIONS: 'true'
    ports:
    - 8443:8080
    volumes:
    - ./:/home/coder/project
    networks:
    - velocelog-net
networks:
  velocelog-net:
    driver: bridge
