apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stack-ecommerce-mlops
resources:
- namespace.yaml
- configmap.yaml
- secret.yaml
- postgres.yaml
- redis.yaml
- minio.yaml
- qdrant.yaml
