apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-mlops-secret
  namespace: stack-ecommerce-mlops
type: Opaque
stringData:
  POSTGRES_PASSWORD: postgres_secure_pass
  MINIO_ROOT_PASSWORD: password123
  RABBITMQ_DEFAULT_PASS: guest
