apiVersion: v1
kind: Secret
metadata:
  name: crypto-trading-stream-secret
  namespace: stack-crypto-trading-stream
type: Opaque
stringData:
  DEFAULT_USER: crypto_admin
  DEFAULT_PASSWORD: vaultSecret999
  POSTGRES_PASSWORD: vaultSecret999
  MINIO_ROOT_PASSWORD: vaultSecret999
  RABBITMQ_DEFAULT_PASS: vaultSecret999
