apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong
  namespace: stack-devops-edge-stack
  labels:
    app: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong
  template:
    metadata:
      labels:
        app: kong
    spec:
      containers:
      - name: kong
        image: kong:3.6
        ports:
        - containerPort: 8000
          name: proxy
        - containerPort: 8001
          name: admin
        - containerPort: 8002
          name: gui
        env:
        - name: KONG_DATABASE
          value: "off"
        - name: KONG_PROXY_ACCESS_LOG
          value: "/dev/stdout"
        - name: KONG_ADMIN_ACCESS_LOG
          value: "/dev/stdout"
---
apiVersion: v1
kind: Service
metadata:
  name: kong
  namespace: stack-devops-edge-stack
  labels:
    app: kong
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    name: proxy
  - port: 8001
    targetPort: 8001
    name: admin
  - port: 8002
    targetPort: 8002
    name: gui
  selector:
    app: kong
