apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stack-devops-edge-stack
resources:
- namespace.yaml
- configmap.yaml
- secret.yaml
- postgres.yaml
- redis.yaml
- nginx.yaml
- apigateway.yaml
- vscode.yaml
