apiVersion: v1
kind: Secret
metadata:
  name: devops-edge-stack-secret
  namespace: stack-devops-edge-stack
type: Opaque
stringData:
  DEFAULT_USER: devops_lead
  DEFAULT_PASSWORD: edgeSecure456
  POSTGRES_PASSWORD: edgeSecure456
  MINIO_ROOT_PASSWORD: edgeSecure456
  RABBITMQ_DEFAULT_PASS: edgeSecure456
